'use strict';
//test
export const TEST = 'TEST';

export const LOAD_LOCAL_USER ='LOAD_LOCAL_USER';

//登录
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const SET_USER_INFO_SUCCESS = 'SET_USER_INFO_SUCCESS';
export const HIDE_LOADING = 'HIDE_LOADING'
export const CLEAR_AUTH ='CLEAR_AUTH'
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
//首页action
export const UPDATE_HOME_INFO = 'UPDATE_HOME_INFO';
export const FETCH_COMPANY_LIST = 'FETCH_COMPANY_LIST';
export const FETCH_COMPANY_LIST2 = 'FETCH_COMPANY_LIST2';



export const FETCH_SEARCH_COMPANY_LIST = 'FETCH_SEARCH_COMPANY_LIST';
export const REVEIVE_COMPANY_LIST = 'REVEIVE_COMPANY_LIST';
export const REVEIVE_SEARCH_COMPANY_LIST = 'REVEIVE_SEARCH_COMPANY_LIST';
export const FETCH_BANK_LIST = 'FETCH_BANK_LIST';
export const REVEIVE_BANK_LIST = 'REVEIVE_BANK_LIST';
export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const REVEIVE_USER_LIST = 'REVEIVE_USER_LIST';
export const FETCH_ENTERPRISE_SET = 'FETCH_ENTERPRISE_SET';
export const REVEIVE_ENTERPRISE_SET = 'ENTERPRISE_SET';
export const USER_LIST_CHANGE = 'USER_LIST_CHANGE';
export const CLEAR_STATUS = 'CLEAR_STATUS';
export const FETCH_ENTERPRISE_INFO = 'FETCH_ENTERPRISE_INFO';
export const REVEIVE_ENTERPRISE_INFO = 'REVEIVE_ENTERPRISE_INFO';


//我的企业
export const FETCH_USER_LOAN_LIST = 'FETCH_USER_LOAN_SET';
export const REVEIVE_USER_LOAN_LIST = 'REVEIVE_USER_LOAN_SET';
export const HIDE_USER_LOAN_LOADING = 'HIDE_USER_LOAN_LOADING';

export const FETCH_ENTERPRISE_DETAIL = 'FETCH_ENTERPRISE_DETAIL';
export const CLEAR_LAST_ENTERPRISE_DETAIL = 'CLEAR_LAST_ENTERPRISE_DETAIL';
export const HIDE_ENTERPRISE_LOADING = 'HIDE_ENTERPRISE_LOADING';

//应用
export const RESOURCE_UPLOAD = "RESOURCE_UPLOAD"
export const COLLECTION_CONFIG= "COLLECTION_CONFIG";
export const SUBMIT_FINDING = "SUBMIT_FINDING";
export const FETCH_FINDING_ENTERPRISE = "FETCH_FINDING_ENTERPRISE"

//storeage
export const COLLECTION_LOCAL = "COLLECTION_LOCAL"
export const FETCH_LOCAL_ENTERPRISE_DETAIL = 'FETCH_LOCAL_ENTERPRISE_DETAIL';
export const REFRESH_ENTERPRISE_DETAIL = 'REFRESH_ENTERPRISE_DETAIL';

//消息
export const FETCH_MESSAGE_LIST = 'FETCH_MESSAGE_LIST';
export const RECEIVE_MESSAGE_LIST = 'RECEIVE_MESSAGE_LIST';
export const SET_MESSAGE_READ = 'SET_MESSAGE_READ';
export const RECEIVE_MAIN_MESSAGE_LIST = 'RECEIVE_MAIN_MESSAGE_LIST';

//话术
export const FETCH_RESPONSE_LIST = 'FETCH_RESPONSE_LIST';
export const RECEIVE_RESPONSE_LIST = 'RECEIVE_RESPONSE_LIST';
export const HIDE_RESPONSE_LIST_LOADING = 'HIDE_RESPONSE_LIST_LOADING';
export const FETCH_RESPONSE_DETAIL = 'FETCH_RESPONSE_DETAIL';
export const RECEIVE_RESPONSE_DETAIL = 'RECEIVE_RESPONSE_DETAIL';
export const CLEAR_RESPONSE = 'CLEAR_RESPONSE';

export const FETCH_RESPONSE_SEARCH = 'FETCH_RESPONSE_SEARCH';
export const RECEIVE_RESPONSE_SEARCH = 'RECEIVE_RESPONSE_SEARCH';
export const CLEAR_RESPONSE_SEARCH = 'CLEAR_RESPONSE_SEARCH';
export const HIDE_RESPONSE_SEARCH_LOADING = 'HIDE_RESPONSE_SEARCH_LOADING';