'use strict';
//test
export const FETCH_REDDIT_LIST = 'FETCH_ARTICLE_LIST';

export const LOAD_LOCAL_USER ='LOAD_LOCAL_USER';

//登录
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const SET_USER_INFO_SUCCESS = 'SET_USER_INFO_SUCCESS';
export const HIDE_LOADING = 'HIDE_LOADING'
export const CLEAR_AUTH ='CLEAR_AUTH'
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
//首页action
export const UPDATE_HOME_INFO = 'UPDATE_HOME_INFO';
export const FETCH_COMPANY_LIST = 'FETCH_COMPANY_LIST';